In [1]:
import numpy as np

arr = np.arange(1, 11)

reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
import numpy as np

arr = np.arange(1, 21)

extracted_elements = arr[5:16]  
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [5]:
import pandas as pd

data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)

series['pears'] = 4

print(series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [9]:
import pandas as pd

# Creating the dataframe
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Hannah", "Ian", "Jack"],
    "age": [25, 30, 22, 35, 28, 40, 26, 32, 29, 27],
    "gender": ["Female", "Male", "Male", "Male", "Female", "Male", "Female", "Female", "Male", "Male"]
}

df = pd.DataFrame(data)
print(df)


      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   35    Male
4     Emma   28  Female
5    Frank   40    Male
6    Grace   26  Female
7   Hannah   32  Female
8      Ian   29    Male
9     Jack   27    Male


In [11]:
import pandas as pd


data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Hannah", "Ian", "Jack"],
    "age": [25, 30, 22, 35, 28, 40, 26, 32, 29, 27],
    "gender": ["Female", "Male", "Male", "Male", "Female", "Male", "Female", "Female", "Male", "Male"]
}

df = pd.DataFrame(data)


occupations = ["Programmer", "Manager", "Analyst", "Programmer", "Manager",
               "Analyst", "Programmer", "Manager", "Analyst", "Programmer"]

df["occupation"] = occupations


print(df)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4     Emma   28  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   26  Female  Programmer
7   Hannah   32  Female     Manager
8      Ian   29    Male     Analyst
9     Jack   27    Male  Programmer


In [13]:

df_filtered = df[df["age"] >= 30]


print(df_filtered)


     name  age  gender  occupation
1     Bob   30    Male     Manager
3   David   35    Male  Programmer
5   Frank   40    Male     Analyst
7  Hannah   32  Female     Manager


In [15]:

df.to_csv("data.csv", index=False)


df_read = pd.read_csv("data.csv")


print(df_read)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4     Emma   28  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   26  Female  Programmer
7   Hannah   32  Female     Manager
8      Ian   29    Male     Analyst
9     Jack   27    Male  Programmer
